from __future__ import annotations

import argparse
from pathlib import Path

from glitch_detection.tempglitch import write_tempglitch_full_video_labels

ROOT = Path(__file__).resolve().parents[1]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert TempGlitch metadata and a merged manifest into labels CSV."
    )
    parser.add_argument(
        "--metadata",
        type=Path,
        default=ROOT / "data" / "raw" / "tempglitch_smoke" / "metadata.csv",
        help="TempGlitch metadata CSV generated by the downloader.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        required=True,
        help="Merged TempGlitch manifest.csv path.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "data" / "raw" / "tempglitch_smoke_labels.csv",
        help="Output labels CSV path.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    output_path = write_tempglitch_full_video_labels(
        metadata_path=args.metadata,
        manifest_path=args.manifest,
        output_path=args.output,
    )
    print(f"Labels: {output_path}")


if __name__ == "__main__":
    main()
